site_name: Cornstarch Project
site_author: Cornstarch team
site_description: Distributed Multimodal LLM training framework

repo_name: SymbioticLab/Cornstarch
repo_url: https://github.com/SymbioticLab/Cornstarch

copyright: Copyright &copy; 2025 Cornstarch team

theme:
  name: material
  logo: assets/images/cornstarch.svg
  favicon: assets/images/favicon.svg
  palette:
    scheme: slate
    primary: amber

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - meta
  - abbr
  - admonition
  - attr_list
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
      linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Cornstarch: index.md
  - Installation: getting_started/installation.md
  - Using Cornstarch:
    - Creating a MLLM model: using_cornstarch/creating_mllm.md
    - Training a MLLM model: using_cornstarch/training_mllm.md
  - Distributed Training:
    - Overview: parallelization/index.md
    - Using DDP/FSDP: parallelization/ddp_fsdp.md
    - Tensor Parallelism: parallelization/tensor_parallel.md
    - Cornstarch Multimodal-Aware 4D Parallelism: parallelization/cornstarch_parallel.md
  - Source Code Reference: reference/