[project]
name = "oobleck-colossalai"
description = "A backend submodule for Oobleck that executes heterogeneous pipelines on ColossalAI."
readme = "README.md"
license = {file = "LICENSE.txt"}
requires-python = ">=3.10"
version = "0.0.1"
authors = [
    {name = "Insu Jang", email = "insujang@umich.edu"}
]
maintainers = [
    {name = "Insu Jang", email = "insujang@umich.edu"}
]
dependencies = [
    "torch",
    "transformers>=4.36.0",
    "colossalai==0.35",
    "loguru",
]

[project.optional-dependencies]
dev = [
    "torch>=2.1.0",
    "ruff",
    "black>=23.0",
    "isort>=5.12",
    "pytest",
    "pytest-mock",
    "expecttest",
]

[tool.ruff]
# Never enforce `E501` (line length violations).
ignore = ["E501"]

[build-system]
requires = ["setuptools>=63.0.0", "wheel"]
build-backend = "setuptools.build_meta"